/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bird.glb --transform 
Files: bird.glb [192.29KB] > /mnt/d/Downloads/bird-transformed.glb [52.62KB] (73%)
Author: Kyan0s (https://sketchfab.com/kyan0s)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flying-crow-blacksmiths-workshop-assets-3ecfc0834b5b4883b840d0426c267efe
Title: Flying Crow - Blacksmith's workshop assets
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

function Bird({ position, speed, pathOffset, scale }) {
  const { nodes, materials } = useGLTF("/model/bird.glb");
  const birdRef = useRef();

  useFrame((state) => {
    if (birdRef.current) {
      const time = state.clock.getElapsedTime() * speed;
      
      // Fly in a circular arc across the sunset
      const radius = 30;
      birdRef.current.position.x = Math.sin(time + pathOffset) * radius + position[0];
      birdRef.current.position.y = Math.sin(time * 0.5 + pathOffset) * 3 + position[1];
      birdRef.current.position.z = Math.cos(time + pathOffset) * radius + position[2];
      
      // Make bird face direction of movement
      birdRef.current.rotation.y = time + pathOffset + Math.PI / 2;
      
      // Gentle wing flapping motion (tilt)
      birdRef.current.rotation.z = Math.sin(time * 8) * 0.1;
    }
  });

  return (
    <group ref={birdRef} scale={scale} dispose={null}>
      <mesh
        geometry={nodes.flyingCrow_0.geometry}
        material={materials.crow01}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

export function Birds(props) {
  return (
    <group {...props}>
      {/* Multiple birds with different paths and speeds */}
      <Bird position={[0, 15, -20]} speed={0.2} pathOffset={0} scale={0.8} />
      <Bird position={[10, 18, -25]} speed={0.15} pathOffset={2} scale={0.9} />
      <Bird position={[-15, 20, -30]} speed={0.18} pathOffset={4} scale={0.7} />
      <Bird position={[5, 16, -22]} speed={0.22} pathOffset={1.5} scale={0.85} />
      <Bird position={[-8, 17, -28]} speed={0.25} pathOffset={3} scale={0.75} />
      <Bird position={[12, 19, -35]} speed={0.17} pathOffset={5} scale={0.8} />
      <Bird position={[-5, 14, -18]} speed={0.21} pathOffset={6.5} scale={0.9} />
      <Bird position={[8, 21, -32]} speed={0.19} pathOffset={7} scale={0.85} />
    </group>
  );
}

useGLTF.preload("/model/bird.glb");
