/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Untitled.glb --transform 
Files: Untitled.glb [22.24MB] > /mnt/d/Downloads/ram-temple2/source/Untitled-transformed.glb [1.32MB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model2(props) {
  const { nodes, materials } = useGLTF('/model/model2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Rose Gold Marble']} rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube_37_1.geometry} material={materials['Brushed Rose Gold']} />
        <mesh geometry={nodes.Cube_37_2.geometry} material={materials['Material 3']} />
        <mesh geometry={nodes.Cube_37_3.geometry} material={materials['Material 1']} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/model2.glb')
